apiVersion: v1
kind: Service
metadata:
  name: nucleotidz-api-service
  labels:
    app: nucleotidz-api
    product: nucleotidz
spec:
  type: ClusterIP
  selector:
    app: nucleotidz-api
  ports:
    - port: 5000
      targetPort: "api"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nucleotidz-external
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - #{ingress-url}#
    secretName: #{ssl-cert-name}#

  rules:
  - host: #{ingress-url}#
    http:
      paths:
      - path: /nucleotidz-api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: nucleotidz-api-service
            port:
              number: 5000